style = "blue"
# I prefer GeometryPredicates style.
pipe_to_function_call = false
always_use_return = false


#
# SciMLStyle diffs from defaults:
#
# whitespace_ops_in_indices = true
# remove_extra_newlines = true
# always_for_in = true
# whitespace_typedefs = true
# normalize_line_endings = "unix"

#
# EAS style diffs from defaults:
#
# always_for_in = true
# always_use_return = true
# import_to_using = true
# join_lines_based_on_source = true
# pipe_to_function_call = true
# remove_extra_newlines = true
# separate_kwargs_with_semicolon = true
# short_to_long_function_def = true
# whitespace_in_kwargs = false
# whitespace_ops_in_indices = true

#
# Blue style diffs from defaults
#
# always_for_in = true
# always_use_return = true
# annotate_untyped_fields_with_any = false
# import_to_using = true
# pipe_to_function_call = true
# remove_extra_newlines = true
# separate_kwargs_with_semicolon = true
# short_to_long_function_def = true
# whitespace_in_kwargs = false
# whitespace_ops_in_indices = true
