name = "TokamakNeutronSource"
uuid = "b9cabe2b-166f-490c-9eed-ccf8ae448f22"
authors = ["dvp2015 <dmitri_portnov@yahoo.com>"]
version = "0.1.0"

[compat]
julia = "1.8.3"

[extras]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Markdown", "Test"]
